"""Regenerates docs/TOOLS.md from the live tool registry:  python scripts/gen_tool_docs.py"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from nova import context  # noqa: E402
from nova.config import load_config  # noqa: E402
from nova.extensions import load_plugins  # noqa: E402
from nova.skills import load_all  # noqa: E402
from nova.tools import GROUP_KEYWORDS, REGISTRY  # noqa: E402

context.cfg = load_config(ROOT / "config.example.yaml")
load_all()
load_plugins()

TITLES = {"system": "System & PC control", "brain": "Memory & 2nd brain", "files": "Files & folders",
          "web": "Web search, scraping & website builder", "browser": "Browser control",
          "google": "Google Workspace", "media": "Video, audio & images", "camera": "Webcam & ads",
          "maintenance": "Updates, rollback & extensions", "currency": "Plugin: currency (example)"}
out = ["# Tool reference", "",
       "_Generated by `python scripts/gen_tool_docs.py` — every ability Nova's model can call._", "",
       "🔒 = asks you to confirm (yes/no) before running.", ""]
groups: dict[str, list] = {}
for t in REGISTRY.values():
    groups.setdefault(t.group, []).append(t)
for g, tools in groups.items():
    out += [f"## {TITLES.get(g, g)}", ""]
    kws = GROUP_KEYWORDS.get(g)
    out += [f"Offered to the model when you say things like: _{', '.join(kws[:12])}_" if kws else
            "Always available.", "", "| Tool | What it does | Parameters |", "|---|---|---|"]
    for t in tools:
        params = ", ".join(f"`{k}`" + ("" if k in t.parameters.get("required", []) else "?")
                           for k in t.parameters.get("properties", {}))
        out.append(f"| `{t.name}`{' 🔒' if t.confirm else ''} | {t.description} | {params or '—'} |")
    out.append("")
(ROOT / "docs" / "TOOLS.md").write_text("\n".join(out), encoding="utf-8")
print(f"docs/TOOLS.md: {len(REGISTRY)} tools in {len(groups)} groups")
